---
# Organization to pull metrics from
organization: 'wiredtiger'

# Start date to pull metrics from
since: '2024-03-04'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-metrics-dashboard'
